### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by fovekorea** [jsh-me/CCTVDetection#1]
코렙으로만 사용하신건가요?
잘 몰라서  어떻게 실행 하는지 알려주실수 있나요?

**Comment by jsh-me** [comment]
@fovekorea 
얼굴 추출까지는 코랩으로 실행되었으며 사용하려는 파일을 코랩 내 파일탐색기에 넣으신 후 바로 진행하시면 될 듯 싶습니다:)
추출된 얼굴을 바탕으로 3D face를 진행하는 과정은 https://github.com/microsoft/Deep3DFaceReconstruction
이 곳을 참고하시면 됩니다.

**Comment by fovekorea** [comment]
![1](https://user-images.githubusercontent.com/48745143/77495619-7d024900-6e8c-11ea-9ddf-b836e91d9bdb.jpg)

여기서 이미지를 넣는건가요? 오류가나네요

**Comment by jsh-me** [comment]
코랩 내부에 있는 mkdir 커맨드 전체에 -p를 붙여주시면 될 듯 싶습니다.
ex)
!mkdir **-p** /content/gdrive/My\ Drive/darknet/data/result

**Comment by fovekorea** [comment]
![2](https://user-images.githubusercontent.com/48745143/77501511-9a8adf00-6e9b-11ea-9a20-f29162890b2e.jpg)

잘몰라서 이건 어떻게 하나요?

**Comment by jsh-me** [comment]
@fovekorea 
해당 커맨드는 /usr/bin/g* 경로를 /usr/local/cuda/bin/g* 로 심볼릭 링크를 걸어주는 단계입니다.
편의성을 위해 작성한 코드이니 생략하셔도 무방합니다. (파일 탐색기에서 폴더 및 파일이 잘 생성 되었는지, 경로는 올바른지 확인 후 경로 수정만 하면 됨)
그리고 심볼릭 링크 경로를 확인해보세요. 이미 링크가 걸려있기 때문에 File exists가 나오는 듯 싶습니다.
또한 이미 생성된 파일 및 폴더들은 주석처리하여 실행하시면 됩니다.

참고로 처음 물어보신 질문은 이미지를 넣는 것이 아닌 폴더 생성과정입니다.
코랩은 리눅스기반이기 쉘명령어에 먼저 익숙해지시는 것을 추천드립니다! =>
감사합니다.

**Comment by fovekorea** [comment]
![3](https://user-images.githubusercontent.com/48745143/77560094-53830500-6f00-11ea-9b24-c1a7c68698ff.jpg)

![4](https://user-images.githubusercontent.com/48745143/77560099-54b43200-6f00-11ea-8e2d-f38f0c12aa6f.jpg)

이게 영상을 넣으라는건가요? result에 Face에 넣으면 되나요?

**Comment by jsh-me** [comment]
@fovekorea
**2_Log를 활용한 추출** 부분을 확인해보면 됩니다.
제 repo에 설명이 많이 부족한 듯 하네요.
이번달 안으로 readme에 자세한 설명을 올려놓겠습니다. ^^

**Comment by fovekorea** [comment]
![비디오](https://user-images.githubusercontent.com/48745143/77994131-75e3ab00-7364-11ea-8e92-7a123cc2febe.jpg)

content/gdrive/My\ Drive/darknet/data/data/video_yolo.mp4요기에 영상넣고 했는데 저렇게 뜨네요

**Comment by jsh-me** [comment]
제 경험상 Video Stream Stropped는 경로가 잘못되어서 발생했던 것으로 기억합니다.

**Comment by fovekorea** [comment]
1_YOLO를 위한 가상환경 설정할때 이렇게 뜨네요
![메이크파일에러](https://user-images.githubusercontent.com/48745143/78088726-fa373c00-73ff-11ea-99ea-dadae0932853.jpg)

**Comment by fovekorea** [comment]
![정확도 100추출](https://user-images.githubusercontent.com/48745143/78090136-44222100-7404-11ea-87d8-2538c8fe259d.jpg)
이건 왜 오류가 뜨는건가요?

**Comment by fovekorea** [comment]
![정확도 100추출](https://user-images.githubusercontent.com/48745143/78091091-fb1f9c00-7406-11ea-85f2-607caae55f62.jpg)
순서대로 하고 있는데 이건 왜 오류가 뜨나요?

**Comment by fovekorea** [comment]
![파일업로드](https://user-images.githubusercontent.com/48745143/78093002-340e3f80-740c-11ea-8c6e-4b94c958f359.jpg)
파일업로드는 여기다 하는건가요?

**Comment by fovekorea** [comment]
![테스트 페이스 아이디](https://user-images.githubusercontent.com/48745143/78121759-c16e8580-7446-11ea-8995-d9fead349206.jpg)
테스트페이스아이디와 파일네임에 뭘 쓰는건가요?

**Comment by fovekorea** [comment]
![파일네임오류1](https://user-images.githubusercontent.com/48745143/79687651-c5dad100-8283-11ea-9c5f-24f6656ec906.jpg)
![파일네임오류2](https://user-images.githubusercontent.com/48745143/79687653-c70bfe00-8283-11ea-8564-cc4011a3f50b.jpg)

1번사진 오류가나서 2번사진처럼 했는데 
테스트페이스아이디와  파일네임에 뭘 쓰는건가요??

**Comment by jsh-me** [comment]
@fovekorea 
바빠서 답변이 늦었네요 죄송합니다.
수정할 필요 없이 빈 배열로 선언하면 for문으로 인해 파일의 경로가 append되고, 그 경로로 try-except가 실행이 됩니다. 해당 파일이 없어서 발생하는 문제 같은데요. cur_dir에 해당하는 파일을 넣어주시면 될듯 합니다. 
3DReconstruction 관련 내용은 microsoft github을 참고하시면 됩니다.

**Comment by fovekorea** [comment]
바쁘신데 죄송합니다:D

다시 해보니 이런 에러가 떠서
Error code: 401
Message: Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

ㅁㅁㅁ

이거 발급 받아서 3-1 (PATH) Person profile에 키값을 수정했는데 안되네요 
이렇게 하는게 맞나요?

![face api발급1](https://user-images.githubusercontent.com/48745143/79740901-5aecd100-833b-11ea-83cd-55d6783dd53a.jpg)
 
 혹시 파란색이나 다른것은 수정안해도 되는건가요?

**Comment by jsh-me** [comment]
@fovekorea 
발급받으신 API를 넣으시면 됩니다!

저 부분 부터는 제가 짠게 아니어서 정확한 답변이 힘들 수 있습니다.ㅠㅠ
오류 내용을 보아하니 client 오류인듯 한데 api를 정확히 입력하면 정상적으로 작동할 듯 싶습니다.
그리고 첨부파일 **(API 캡쳐본)** 은 지우시는게 좋으실 듯 싶어요!

**Comment by fovekorea** [comment]
첨부파일이라는게 무슨 말씀인가요?

**Comment by fovekorea** [comment]
![파일네임오류3](https://user-images.githubusercontent.com/48745143/79832555-a27b6780-83e4-11ea-8cbc-8b9cfa83aa0f.png)

해당 폴더에 해당png파일이 있는데 저렇게 뜨는데 왜그런지 알수 있을까요?

**Comment by fovekorea** [comment]
혹시 demo.py파일은 어느 경로에 넣어야 하는지 알수 있을까요?
어디다 넣어야 하는지 모르겠어서요

**Comment by jsh-me** [comment]
https://github.com/microsoft/Deep3DFaceReconstruction
참고하시면 됩니다.
demo.py 는 colab에서 만들어진 데이터를 local로 다시 다운받아서 local 환경에서 돌려야 할거에요. 
demo.py 실행 시 GUI가 실행되어서 colab에서는 정상적으로 작동하지 않을 수 있습니다.

**Comment by fovekorea** [comment]
Python >= 3.5 (numpy, scipy, pillow, opencv).
Tensorflow 1.4 ~ 1.12. 
이것도 코드로 해서 설치하는건가요?잘아는게 아니라서 코드를 어떻게 해야 될까요?

**Comment by jsh-me** [comment]
다 설치하시면 됩니다~ 코랩은 아마 tensorflow 2.xx 가 default 일거에요. 그래서 가상환경 구성을 잘하셔야 합니다.

**Comment by fovekorea** [comment]
![데모 아웃풋](https://user-images.githubusercontent.com/48745143/80079269-05a6fe80-858b-11ea-963a-95a1ad99e63e.jpg)

3d face 링크로 들어가서 거기있는 깃으로 테스트 파일을 실행해봤는데 output폴더에
 "xxx.mat","xxx_mesh.obj" 이렇게 생겼는데 저걸 어떻게 하는건가요?

**Comment by fovekorea** [comment]
demo.py 는 colab에서 만들어진 데이터를 local로 다시 다운받아서 local 환경에서 돌려야 할거에요.
demo.py 실행 시 GUI가 실행되어서 colab에서는 정상적으로 작동하지 않을 수 있습니다.

말씀해주신 말이 이해가 잘안되서  자세히 설명해주실수 있나요?
일단 3dFace링크에 있는 연습코드로 실행을 해서 .obj 파일까지는 나왔습니다.
![데모 아웃풋](https://user-images.githubusercontent.com/48745143/80303830-a8f74e00-87ed-11ea-9387-0f916a6e055b.jpg)

**Comment by fovekorea** [comment]
![데모 아웃풋](https://user-images.githubusercontent.com/48745143/80436407-039dc080-893a-11ea-8509-da30e8928623.jpg)

사진처럼 mess-obj까지 추출했는데 이걸 어떻게 하나요?

**Comment by fovekorea** [comment]
![3dface 피글렛 오류](https://user-images.githubusercontent.com/48745143/80438016-1f0aca80-893e-11ea-88ae-245d8c1f1f6e.jpg)

마지막 코드를 실행할때 이런 오류가 뜨는건 왜그런건가요?
mess.obj 파일은 3DFace/output/input 폴더에 넣었는데 맞나요

**Comment by fovekorea** [comment]
mess.obj파일을 만들었는데 이걸 이제 어떻게 하는건가요?
